# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import clip_pb2 as clip__pb2


class HelloStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HelloPython = channel.unary_unary(
                '/Hello/HelloPython',
                request_serializer=clip__pb2.RequestHello.SerializeToString,
                response_deserializer=clip__pb2.ResultHello.FromString,
                )


class HelloServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HelloPython(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HelloServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HelloPython': grpc.unary_unary_rpc_method_handler(
                    servicer.HelloPython,
                    request_deserializer=clip__pb2.RequestHello.FromString,
                    response_serializer=clip__pb2.ResultHello.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Hello', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Hello(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HelloPython(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Hello/HelloPython',
            clip__pb2.RequestHello.SerializeToString,
            clip__pb2.ResultHello.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
