# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clip.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nclip.proto\"\x1c\n\x0cRequestHello\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\x0bResultHello\x12\x0e\n\x06result\x18\x01 \x01(\t23\n\x05Hello\x12*\n\x0bHelloPython\x12\r.RequestHello\x1a\x0c.ResultHellob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clip_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTHELLO']._serialized_start=14
  _globals['_REQUESTHELLO']._serialized_end=42
  _globals['_RESULTHELLO']._serialized_start=44
  _globals['_RESULTHELLO']._serialized_end=73
  _globals['_HELLO']._serialized_start=75
  _globals['_HELLO']._serialized_end=126
# @@protoc_insertion_point(module_scope)
